[feat] add tilelang mhc head compute mix
Co-authored-by: zouqian<zouqian4@huawei.com>



# message auto-generated for no-merge-commit merge:
!485 merge tilelang_add_mhc_head_compute_mix into master

[feat] add tilelang mhc head compute mix

Created-by: zouqian
Commit-by: zouqian
Merged-by: cann-robot
Description: ## 描述
mhc_head_compute_mix 是专为多头混合设计的自定义算子，主要用于模型中 HcHead 模块的前向与反向计算。
替换后验证训练正常收敛，compile模式运行通过，性能为ascend c的85%。
通过配置项npu_mhc_head_compute_mix_tilelang控制，默认不打开。

算子实现代码来源开源社区：https://github.com/tile-ai/tilelang-ascend/blob/ascendc_pto/examples/tile_kernels/
mhc/head_compute_mix_kernel.py

## 类型
- [ ] Bug 修复
- [x] 新功能
- [ ] 重构（即不是新增功能，也不是修改bug的代码变动）
- [ ] 构建过程或辅助工具的变动
- [ ] 文档内容更新

## Checklist:
- [x] 我的代码遵循这个项目的代码风格
- [x] 我已经自己测试过我的代码
- [x] 我已经更新了相应的文档
- [x] 我已经在标题中正确使用了类型标签（例如：`feat`, `fix`, `refactor`, `docs`, `test`）

## 如何测试
在注册时打开配置项
torchtitan-npu/torchtitan_npu/models/deepseek_v4/config_registry.py
_DEFAULT_CONVERTERS = ("npu_mhc_head_compute_mix_tilelang", "npu_rms_norm", "npu_moe_dispatch", "npu_gmm", "npu_rope", "npu_smla", "npu_mhc_pre") 
运行单节点训练脚本
NGPU=16 LOG_RANK=0 bash examples/deepseek_v4/debug_deepseek_v4_single_node.sh
[rank0]:[titan] 2026-07-29 16:04:10,302 - root - INFO - step:  1  loss: 16.00585  grad_norm: 12.5553  memory: 42.87GiB(69.97%)  tps: 114  tflops: 24.96  mfu: 8.00%  elapsed_time_per_step: 35.875s
[rank0]:[titan] 2026-07-29 16:04:10,304 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.0028995235916227102
[rank0]:[titan] 2026-07-29 16:04:10,304 - root - INFO - Synchronizing and adjusting timeout for all ProcessGroups to 0:01:40
[rank0]:[titan] 2026-07-29 16:04:20,529 - root - INFO - step:  2  loss: 15.35939  grad_norm: 11.0819  memory: 42.88GiB(69.98%)  tps: 401  tflops: 87.58  mfu: 28.07%  elapsed_time_per_step: 10.225s
[rank0]:[titan] 2026-07-29 16:04:20,533 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.002819751389324665
[rank0]:[titan] 2026-07-29 16:04:30,808 - root - INFO - step:  3  loss: 14.50843  grad_norm:  8.3586  memory: 42.88GiB(69.98%)  tps: 399  tflops: 87.17  mfu: 27.94%  elapsed_time_per_step: 10.274s
[rank0]:[titan] 2026-07-29 16:04:30,809 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.0026563710998743773
[rank0]:[titan] 2026-07-29 16:04:41,024 - root - INFO - step:  4  loss: 14.24559  grad_norm: 34.2183  memory: 42.88GiB(69.98%)  tps: 401  tflops: 87.70  mfu: 28.11%  elapsed_time_per_step: 10.211s
[rank0]:[titan] 2026-07-29 16:04:41,025 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.0023927013389766216
[rank0]:[titan] 2026-07-29 16:04:51,250 - root - INFO - step:  5  loss: 14.12058  grad_norm: 21.6977  memory: 42.88GiB(69.98%)  tps: 401  tflops: 87.58  mfu: 28.07%  elapsed_time_per_step: 10.225s
[rank0]:[titan] 2026-07-29 16:04:51,255 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.0021433415822684765
[rank0]:[titan] 2026-07-29 16:05:01,541 - root - INFO - step:  6  loss: 13.85813  grad_norm:  8.4132  memory: 42.88GiB(69.98%)  tps: 398  tflops: 87.06  mfu: 27.90%  elapsed_time_per_step: 10.286s
[rank0]:[titan] 2026-07-29 16:05:01,543 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.0021830732002854347
[rank0]:[titan] 2026-07-29 16:05:11,763 - root - INFO - step:  7  loss: 13.64883  grad_norm:  6.9568  memory: 42.88GiB(69.98%)  tps: 401  tflops: 87.65  mfu: 28.09%  elapsed_time_per_step: 10.217s
[rank0]:[titan] 2026-07-29 16:05:11,764 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.0020301914773881435
[rank0]:[titan] 2026-07-29 16:05:22,017 - root - INFO - step:  8  loss: 13.20565  grad_norm:  5.9639  memory: 42.88GiB(69.98%)  tps: 400  tflops: 87.34  mfu: 27.99%  elapsed_time_per_step: 10.253s
[rank0]:[titan] 2026-07-29 16:05:22,022 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.0018255757167935371
[rank0]:[titan] 2026-07-29 16:05:32,269 - root - INFO - step:  9  loss: 13.02160  grad_norm:  4.1837  memory: 42.88GiB(69.98%)  tps: 400  tflops: 87.39  mfu: 28.01%  elapsed_time_per_step: 10.247s
[rank0]:[titan] 2026-07-29 16:05:32,271 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.0017025293782353401
[rank0]:[titan] 2026-07-29 16:05:42,522 - root - INFO - step: 10  loss: 13.02039  grad_norm:  4.3851  memory: 42.88GiB(69.98%)  tps: 400  tflops: 87.38  mfu: 28.01%  elapsed_time_per_step: 10.249s
[rank0]:[titan] 2026-07-29 16:05:42,524 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.0015952133107930422
[rank0]:[titan] 2026-07-29 16:05:42,524 - root - INFO - Sleeping 2 seconds for other ranks to complete
[rank0]:[titan] 2026-07-29 16:05:44,524 - root - INFO - Training completed
[rank0]:[titan] 2026-07-29 16:05:45,396 - root - INFO - Process group destroyed


compile模式：
NGPU=16 LOG_RANK=0 bash examples/deepseek_v4/debug_deepseek_v4_single_node.sh --compile.enable
[rank0]:[titan] 2026-07-29 16:49:08,053 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - Compiling each TransformerBlock with torch.compile
[rank0]:[titan] 2026-07-29 16:49:08,495 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - Applied FSDP to the model
[rank0]:[titan] 2026-07-29 16:49:10,273 - root - WARNING - Error running lspci: [Errno 2] No such file or directory: 'lspci', fallback to use device_name
[rank0]:[titan] 2026-07-29 16:49:10,273 - root - WARNING - Peak flops undefined for: Ascend910_9382, fallback to A100
[rank0]:[titan] 2026-07-29 16:49:10,273 - root - INFO - Peak FLOPS used for computing MFU: 3.120e+14
[rank0]:[titan] 2026-07-29 16:49:10,274 - root - INFO - NPU memory usage for model: 6.49GiB(10.60%)
[rank0]:[titan] 2026-07-29 16:49:10,274 - torchtitan_npu.patches.optimizer.optimizer_selector - INFO - [OptimizerDispatcher] Using SwapOptimizer
[rank0]:[titan] 2026-07-29 16:49:10,281 - torchtitan_npu.patches.optimizer.optimizer_selector - INFO - [SwapOptimizer] Patched Adam/AdamW successfully
[rank0]:[titan] 2026-07-29 16:49:10,289 - torchtitan_npu.patches.optimizer.swap_optimizer - INFO - [SwapOptimizer] Patched AdamW.step and Adam.step
[rank0]:/mnt/sdb/z00447436/code/torchtitan-npu-master/torchtitan-npu/torchtitan_npu/patches/optimizer/swap_optimizer.py:298: UserWarning: Cannot create tensor with interal format while allow_internel_format=False, tensor will be created with base format. (Triggered internally at ../torch_npu/csrc/aten/common/TensorFactories.cpp:348.)
[rank0]:  device_state[key] = torch.zeros_like(param, memory_format=torch.contiguous_format)
[rank0]:[titan] 2026-07-29 16:49:12,389 - torchtitan_npu.patches.optimizer.swap_optimizer - INFO - Swap param numel for optimizer_0: 98281936 / 1572510980
[rank0]:
[rank0]:[titan] 2026-07-29 16:49:12,632 - root - INFO - Mixed precision training is handled by fully_shard or replicate
[rank0]:[titan] 2026-07-29 16:49:12,632 - root - INFO - Trainer is initialized with local batch size 1, global batch size 16, gradient accumulation steps 1, sequence length 4096, total steps 20 (warmup 4)
[rank0]:[titan] 2026-07-29 16:49:12,633 - root - INFO - Training starts at step 1
[rank0]:[NPU] Cleared NPU cache at step 1
[rank0]:[rank0]:W0729 16:49:13.915000 1440240 site-packages/torch/_inductor/codecache.py:841] [0/0] pre_grad_custom_pass function does not implement uuid(); falling back to early timing (pre-grad pass cache will be bypassed). Implement uuid() on your CustomGraphPass to enable caching.
[rank0]:/usr/local/python3.11.15/lib/python3.11/site-packages/torch/_inductor/lowering.py:2412: UserWarning: Torchinductor does not support code generation for complex operators. Performance may be worse than eager.
[rank0]:  warnings.warn(
[rank0]:[titan] 2026-07-29 16:49:21,425 - torchtitan_npu.converters.kernels.gmm - INFO - [GMM-TP] w2 placements=(Shard(dim=0),), is_tp=False, w2 local shape=torch.Size([2, 4096, 2048]), w13 local shape=torch.Size([2, 4096, 4096])
[rank0]:[titan] 2026-07-29 16:49:32,158 - torch_npu.env - INFO - get env TL_ROOT = /data/z00447436/tilelang/tilelang-ascend-0716-ori
[rank0]:[rank0]:W0729 16:49:57.732000 1440240 site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_state.py:385] 1 of the 2 modules passed to fully_shard did not run forward before backward, which is error-prone since FSDP post-forward/pre-backward logic will not run for these modules. We recommend passing only modules that run forward together. Modules that did not run forward: [FSDPNPURMSNorm((4096,), eps=1e-06, elementwise_affine=True)]
[rank0]:[titan] 2026-07-29 16:50:03,717 - root - INFO - step:  1  loss: 15.92760  grad_norm: 12.1762  memory: 36.62GiB(59.77%)  tps: 73  tflops: 16.04  mfu: 5.14%  elapsed_time_per_step: 55.821s
[rank0]:[titan] 2026-07-29 16:50:03,748 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.002831886988133192
[rank0]:[titan] 2026-07-29 16:50:03,748 - root - INFO - Synchronizing and adjusting timeout for all ProcessGroups to 0:01:40
[rank0]:/mnt/sdb/z00447436/code/torchtitan/torchtitan/torchtitan/distributed/utils.py:460: UserWarning: Set timeout is now only supported for either nccl or gloo.
[rank0]:  torch.distributed.distributed_c10d._set_pg_timeout(timeout, group)
[rank0]:[titan] 2026-07-29 16:50:12,104 - root - INFO - step:  2  loss: 15.35909  grad_norm: 11.3053  memory: 36.62GiB(59.77%)  tps: 489  tflops: 106.80  mfu: 34.23%  elapsed_time_per_step: 8.385s
[rank0]:[titan] 2026-07-29 16:50:12,106 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.002795338863506913
[rank0]:[titan] 2026-07-29 16:50:20,450 - root - INFO - step:  3  loss: 14.55091  grad_norm:  7.8676  memory: 36.62GiB(59.77%)  tps: 491  tflops: 107.34  mfu: 34.40%  elapsed_time_per_step: 8.343s
[rank0]:[titan] 2026-07-29 16:50:20,452 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.002649726113304496
[rank0]:[titan] 2026-07-29 16:50:28,814 - root - INFO - step:  4  loss: 14.05702  grad_norm: 19.1264  memory: 36.62GiB(59.77%)  tps: 490  tflops: 107.11  mfu: 34.33%  elapsed_time_per_step: 8.361s
[rank0]:[titan] 2026-07-29 16:50:28,815 - torchtitan_npu.models.deepseek_v4.parallelize - INFO - indexer loss: 0.0024413331411778927
[rank0]:[titan] 2026-07-29 16:50:37,153 - root - INFO - step:  5  loss: 13.98659  grad_norm: 17.1732  memory: 36.62G

See merge request: cann/torchtitan-npu!485